package joonas.niemi.jnotes.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Light
internal val primaryLight = Color(0xFF6E5D00)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFFFE368)
internal val onPrimaryContainerLight = Color(0xFF554800)
internal val secondaryLight = Color(0xFF6B5E24)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFF6E39C)
internal val onSecondaryContainerLight = Color(0xFF544810)
internal val tertiaryLight = Color(0xFF4D6700)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFCBF26F)
internal val onTertiaryContainerLight = Color(0xFF3B5000)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFFFF9EE)
internal val onBackgroundLight = Color(0xFF1E1B11)
internal val surfaceLight = Color(0xFFFFF9EE)
internal val onSurfaceLight = Color(0xFF1E1B11)
internal val surfaceVariantLight = Color(0xFFEBE2C8)
internal val onSurfaceVariantLight = Color(0xFF4C4733)
internal val outlineLight = Color(0xFF7D7761)
internal val outlineVariantLight = Color(0xFFCFC6AD)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF343025)
internal val inverseOnSurfaceLight = Color(0xFFF8F0DF)
internal val inversePrimaryLight = Color(0xFFE5C524)
internal val surfaceDimLight = Color(0xFFE0D9C9)
internal val surfaceBrightLight = Color(0xFFFFF9EE)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFFBF3E2)
internal val surfaceContainerLight = Color(0xFFF5EDDD)
internal val surfaceContainerHighLight = Color(0xFFEFE8D7)
internal val surfaceContainerHighestLight = Color(0xFFE9E2D1)

// Dark
internal val primaryDark = Color(0xFFFFFFFF)
internal val onPrimaryDark = Color(0xFF3A3000)
internal val primaryContainerDark = Color(0xFFF3D334)
internal val onPrimaryContainerDark = Color(0xFF4B3F00)
internal val secondaryDark = Color(0xFFD8C682)
internal val onSecondaryDark = Color(0xFF3A3000)
internal val secondaryContainerDark = Color(0xFF4A3F06)
internal val onSecondaryContainerDark = Color(0xFFE6D48E)
internal val tertiaryDark = Color(0xFFFFFFFF)
internal val onTertiaryDark = Color(0xFF263500)
internal val tertiaryContainerDark = Color(0xFFBCE262)
internal val onTertiaryContainerDark = Color(0xFF334500)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF16130A)
internal val onBackgroundDark = Color(0xFFE9E2D1)
internal val surfaceDark = Color(0xFF16130A)
internal val onSurfaceDark = Color(0xFFE9E2D1)
internal val surfaceVariantDark = Color(0xFF4C4733)
internal val onSurfaceVariantDark = Color(0xFFCFC6AD)
internal val outlineDark = Color(0xFF989079)
internal val outlineVariantDark = Color(0xFF4C4733)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFE9E2D1)
internal val inverseOnSurfaceDark = Color(0xFF343025)
internal val inversePrimaryDark = Color(0xFF6E5D00)
internal val surfaceDimDark = Color(0xFF16130A)
internal val surfaceBrightDark = Color(0xFF3D392E)
internal val surfaceContainerLowestDark = Color(0xFF100E06)
internal val surfaceContainerLowDark = Color(0xFF1E1B11)
internal val surfaceContainerDark = Color(0xFF222015)
internal val surfaceContainerHighDark = Color(0xFF2D2A1F)
internal val surfaceContainerHighestDark = Color(0xFF383529)
